apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-cluster
  region: us-east-1
  
managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    minSize: 0
    maxSize: 3
    desiredCapacity: 2    
    labels:
      lifecycle: OnDemand
      intent: control-apps
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
    ssh: # use existing EC2 key
      publicKeyName: frida-2023
      